# Generated by Django 3.0.6 on 2020-05-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='game_category',
        ),
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
    ]
